spring:
  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:test
     platform: h2
     #schema: classpath:db/h2_table.sql
     #data: classpath:db/h2_data.sql
     username: root
     password: 123123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:chargeDB}?serverTimezone=UTC
#    #如果运行出错，可以把连接写成下面的路径进行测试
#    #url: jdbc:mysql://localhost:3306/blogDB?useUnicode=true&characterEncoding=utf-8
#    username: ${MYSQL_USER_TEST:root}
#    password: ${MYSQL_PASSWORD_TEST:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0

my-name: default
my-age: default
